module.exports = {
  extends: 'airbnb-base',
  plugins: [
    'import'
  ],
  globals: {
    expect: true,
    window: true,
    document: true,
    jest: true,
    test: true,
    fetch: true,
    process: true,
    localStorage: true,
    navigator: true,
    Cypress: true,
    after: true,
    afterAll: true,
    afterEach: true,
    before: true,
    beforeAll: true,
    beforeEach: true,
    context: true,
    cy: true,
    cypress: true,
    describe: true,
    from: true,
    integration: true,
    it: true,
    tests: true,
  },
  rules: {
    camelcase: [0],
    'comma-dangle': [1, {
      arrays: 'only-multiline',
      objects: 'always',
      imports: 'always',
      exports: 'always',
      functions: 'ignore',
    }],
    /* package.json has been deduped, which triggers this on most packages. We
       will disable this rule for now while we figure out a good solution. */
    'import/no-extraneous-dependencies': 0,
    semi: [2, 'never'],
    'arrow-body-style': 0,
    quotes: ['error', 'single'],
    'global-require': 0,
    'no-plusplus': 0,
    'no-param-reassign': [2, { props: false, }],
    'no-mixed-operators': 0,
    'no-continue': 0,
  },
}
