version: 2
jobs:
  test:
    docker:
      - image: node:8.11.2
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Test
          command: npm test
  deploy:
    docker:
      - image: ubuntu:17.10
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            apt update
            apt --yes install \
              jq
      - run:
          name: Tag version if it doesn't exist
          command: |
            TAG="v$(cat package.json | jq -r .version)"
            git tag | grep -q "^$TAG$"

            if [[ $? != "0" ]]; then
              git tag $TAG
              git push origin --tags
            fi

workflows:
  version: 2
  deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
