version: 2
jobs:
  test:
    docker:
      - image: node:8.11.2
    working_directory: ~/repo
    steps:
      - add_ssh_keys
      - checkout
      - run:
          name: Test
          command: npm test
  deploy:
    docker:
      - image: ubuntu:17.10
    working_directory: ~/repo
    steps:
      - add_ssh_keys
      - run:
          name: Setup
          command: |
            apt update
            apt --yes install \
              jq \
              git
      - checkout
      - run:
          name: Tag version if it doesn't exist
          command: |
            TAG="v$(cat package.json | jq -r .version)"
            echo '1'
            git tag
            echo '2'
            echo "v1.0.0" | grep "^$TAG$"
            echo '3'
            HAS_TAG=$(git tag | grep "^$TAG$" | wc -l)

            if [[ $HAS_TAG != "0" ]]; then
              git tag $TAG
              git push origin --tags
            fi

workflows:
  version: 2
  deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
